# **In Depth Review: Highest Offense Calculator**

In [39]:
# --- Setup Notes ---
"""
setup(
    name="CJ_Services",
    version="3.0.0",
    author="Jax L. Fonseca-Folden",
    url="https://www.linkedin.com/in/jaxff",
    install_requires=[
        "numpy>=2.3.4",
        "pandas>=2.3.3"
        "re>=2.2.1"
    ],
    python_requires='>=3.13.8',
)
"""
print("Let's get started!")

Let's get started!

## **Conceptual Design**
The *Highest Offense Calculator* is an object-oriented programming style, designed to provide a practical solution when trying to extract the most serious offense within a case. The programming script has three main features, slicing columns, backfill function, and the calculator itself. The slicer is a standardizing method to ensure consistency of code column throughout any dataset. The backfill feature is an integral part of accuracy, which fills in missing data points and has capabilities in special case handling. Lastly, the calculator itself and the class, which is designed to fit any dataset. Afterwords, all files can be exported as a CSV file or initialized into a python pandas.DataFrame() to be further manipulated.

**Object-Oriented Programming** allows for future ease of change and it offers flexibility in adding more methods/functions to the CJ_Services personal python module!

### *Design Comparison to Previous Attempts*
There are only two other previous attempts of optimizing and improving highest crime calculator. The biggest differences between previous attempts and this one are the ability to fit all datasets & simplicity logic simplicity, which includes special case handling, calculator logic, and more accurate account offense data. 

<u>Data Morphism</u>: Previous attempts required the entirety of the code and necessity to change each section of the script to respective column names. This manual requirement becomes an un-necessary and time-consuming step, which also poses issues with users who have no understanding of python code. With this attempt, the dataset and key columns are specified as part of the initialization of the dataset, allowing data extraction to be as error-free and friendly as possible. Although, users need to learn very basic aspects of python. The simplicity of the new calculator is that the back frame of the code itself is not seen, taking away the complexity and need in programming proficiency. Instead, it is a module import where users can utilize the functions in it.

<u>Special Cases</u>: This script has several areas where it is necessary to exclude or include certain values. In terms of the calculator, the two most important areas of handling exceptions are the standardizing of offense codes and filling the class descriptions. When standardizing the column of offense codes, some datasets had ending digits. These digits correlated to the statute section items or clauses. The ending digits caused issues between 900 codes (homicides) and 9,000 codes (miscellaneous). When executing previous attempts, if a dataset had ending digits, the calculator would classify all serious offenses as low-level miscellaneous offenses. With the improved function for standardizing codes, the script knows whether to extract the first 3 or 4 digits of the code, based on the pattern found. The other case handling issue was with the backfill function. Stated further down, in the *Input Data* section, there are varying values that sometimes hold the offense degree. With previous attempts, the column was wiped and merged with the *All_OffenseCodes.csv* file provided by the state. This meant that any class specification would be re-classified and no longer specific to the original data.

<u>Calculator Logic</u>: Previous calculators re-classify, rank, and sort based on class. This completely excluding the offense code itself, which is deemed by NC State to be a rank aiding with the class. Based on this, alone, if a case were to have two Felony A charges, the algorithm would choose at random which offense to keep as the highest charge. Therefore, at random, two Felony A charges, where one charge may have the higher code number could be chosen to be the more serious offense. This going against the logic of offense codes, as the smallest number correlates to the more serious offense. With this version, the class must be determined first and ranked just like previous versions, with the addition of an extra sorting algorithm. This ensures that the class rank comes first and then the code rank second. If there were to be several counts of the highest offense, it would select the first iteration of the offense, leading to the calculator to not be affected as they are both the same charge.

<u>Offense Codes Data</u>: The data given in this calculator comparative to others is that all offense codes with missing classes for Felonies and Misdemeanors (only) were manually filled in to its perspective potential outcomes. Many offense degree values were missing due to various factors, such as being a 'place holder charge' or being a common law. Due to this, all 'blank', '??', and missing values were filled in to its fullest attempt. This drastically increased accuracy of extraction of specific classes, as the formatting of offenses with several outcomes has been accounted for in the python script and in the file itself. More details are in the *Input Data* section.

### *Limitations*
Just like previous attempts, there are still several limitations within this version. (1) Cleaning data, while this calculator perfectly maintains current data points and fills in missing data points, it still requires manual cleaning of each column. This being an easy fix utilizing statistical software or data visualization platforms. (2) The offense codes data is an incurable limitation, because if an offense code does not exist in this file, then it cannot backfill missing data within the files that need it. As a result, when finding the highest crime with the stipulation of a specific class, this version will automatically exclude anything without a value in the class column. (3) Constant maintenance of the offense code file. It is of most importance that when updates are provided to the codes, that the improved file is also updated to hold current information.

## **Table of Contents**
1. CJ_Services Library Overview
    - Library Imports
    - Class Variables
    - Constructor `cjs.DataSource()`
    - Get Data Method `cjs.Get_Data()`
    - Slice Column Code Method `cjs.SliceCol_Code()`
    - Fill Blank Column Method `cjs.Fill_BlankCol()`
    - Get Dropped Rows Method `cjs.Get_Dropped()`
    - Export File Method `cjs.Export_File()`
    - Calculate Highest Offense Method `cjs.CalcH_HighestOffense()`
2. Input Data
    - Offense Codes File
    - Test Files

3. Demonstration
    - Demo 1: Simplistic Code Review
    - Demo 2: Library Walk Through & Format Options
        - (1) imports
        - (2) initialize offense file
        - (3) initialize cjs.DataSource()
        - (4A) backfill class column
        - (4B) backfill other columns
        - (5A) calculate highest offense
        - (5B) viewing cjs.DataSource() in python file
        - (6) export dataset to CSV
    - Demo 3: Specialized Case Handling
    - Demo 4: Nested Results Comparison (step by step)

## **Class Overview `CJ_Services`**

### *Library Imports*
Four library imports are utilized and must be initiated at the beginning of the programming script: `pandas`, `numpy`, `re`, and `typing`. *Pandas* library is an industry standard data analysis tool, that assists in easy reading, filtering, and exporting files. *Numpy* library is another industry standard tool that is utilized for complex aggregation, scalar functionality, and analytical observations. In this script, numpy is used for string manipulation and special case handling. Regular Expression (*re*) is a specialized function for pattern searching, making sure there are no collisions when searching for a specific letter, word, or phrase. Lastly, *typing* is a library that allows for specified functions to have optional attribute handling.

In [5]:
import pandas as pd
import numpy as np
import re
from typing import Optional, Literal, Union, List

### *Class Variables*
Shared amongst all datasets, the calculator must utilize these variables to properly rank the classes. In the case that the ranking changes, this creation of `class_order` variable makes for easy updates. Due to all class variables being at the top of the module, users can easily find and organize classes to the perspective rankings.

In [6]:
class_order = (
    'A', 'B1', 'B2', 'C', 'D', 'E', 'F', 'H', 'I',
    'A1', '1', '2', '3'
)
class_rank = {cls: i for i, cls in enumerate(class_order)}

### *Constructor*
The first section and most important aspect of object-oriented programming is the constructor. It consists of the class name, the constructor variables, and constructor attributes. This is the key to making the calculator fit a variety of datasets as it stores where the file can be found, and specific columns needed for execution. These columns are the file itself, primary key, the class, and the code. When initializing the dataset, it is optional to initialize either a `pandas.DataFrame()` or a file path. In doing this, it allows for pre- or post-analysis utilizing python. The primary key is how the calculator should group the offenses and most commonly is by case number. However other columns can be substituted in the `_Col_PrimKey` variable, such as the PID number. After initializing the constructor, the dataset will automatically be stripped of leading and ending spaces and assigned to the private variable `_data`. As common practice, an empty private variable called `_newData` will store the edited version of the dataset. Having separate variables allows for easy reversion of data extraction and future use. Lastly, another empty private variable called `_droppedRows` will be created to store all rows that have been dropped from the `cjs.Fill_BlankCol()` method. This method will serve as a integrity check allowing for users to see the invalid values in the `_Col_Code`. Most commonly, this variable will only be utilized if there was a high percentage of rows dropped from the dataset.

**Note:** Primary Key column does not have to be specified and will not prevent the calculator method from functioning.

In [7]:
class DataSource:
    def __init__(
        self, *, 
        CSV_File: Union[str, pd.DataFrame], 
        Col_PrimKey: Optional[str] = None, 
        Col_Class: str, 
        Col_Code: str
    ):
        
        """
        Processes CSV File into python, allowing users to utilize the DataSource class with ease.
        
        Attributes
        ----------
        CSV_File (str | pandas.DataFrame())
            File path, must be CSV
        Col_PrimKey (str | None)
            The column header containing the primary key of the dataset
        Col_Class (str)
            The column header containing the offense class/degree
        Col_Code (str)
            The column header containing the offense code
            
        Local Variables
        ----------
        **_data** : (pandas.DataFrame()) 
            > Stores the initialized data and any post data non-permanent method executions
        **_newData** : (pandas.DataFrame())
            > Stores the data after a non-permanent method is executed
        **_droppedRows** : (pandas.DataFrame())
            > Stores dropped rows from the DataSource.Fill_BlankCol() function
        """
        
        # Initializing constructor variables
        self._CSV_File = CSV_File
        
        # Col_PrimKey Attribute Check
        if Col_PrimKey is not None:
            self._Col_PrimKey = Col_PrimKey
        self._Col_Class = Col_Class
        self._Col_Code = Col_Code
        
        # CSV_File instance check for specific pandas initialization
        if isinstance(CSV_File, str):
            initial_df = pd.read_csv(CSV_File, low_memory=False)
        else: initial_df = CSV_File
        
        # Variables for stripping and storing dataset
        self._data = initial_df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
        self._newData = None
        
        # Variable for storing dropped rows from cjs.Fill_BlankCol()
        self._droppedRows = None

### *Get Data Method* `cjs.Get_Data()`
This method allows for easy access to the original dataset and the dataset after code execution. It is in place because the `DataSource` class will become a module import. Meaning that access to the raw data stored within the class/object will not be accessible unless a specialized method is created to do so. When utilizing this, it will enable users to do further analysis within python and `pandas.DataFrame()` library import. The `Get_Data` has an optional parameter that gives users the ability to specify if they want the 'calculated' data or the 'original' data. If there is no specification, the automatic return will be the most recent or updated dataset. To prevent any confusion, statements specifying which dataset has been returned will be printed for users. At the same time, if a specific dataset is called but does not exist, the function automatically returns an empty variable (known as `None`) and print a statement of the corresponding data structure selected. In the case that a dataset does not exist in either the `_data` or `_newData` variable, the function will implicitly return nothing.

In [8]:
def Get_Data(
    self, 
    Data: Optional[Literal["calculated data", "original data"]] = None
):
    
    """
    Retrieves data into python to utilize Pandas Library methods.
    
    Parameters
    ----------
    Data ("calculated data" | "original data")(OPTIONAL)
        Specifies which type of data retrieved
                
    Returns
    ----------
    pandas.DataFrame()
        If data exist, returning data as a pandas DataFrame
    None
        If data does not exist, returning None
    """
    
    # Execution if attribute is specified
    if Data == "calculated data":
        if self._newData is not None:
            print("Returning Calculated Data")
            return self._newData
        print("Data has not been calculated")
        return
    elif Data == "original data":
        if self._data is not None:
            print("Returning Original Data")
            return self._data
        print("Data has not been intialized")
        return

    # Execution if parameter is not specified
    elif Data is None:
        if self._newData is not None:
            print("Returning Calculated Dataset")
            return self._newData
        elif self._data is not None:
            print("Returning Original Dataset")
            return self._data
            
        # Execution if function has no dataset
        print("No Existing Dataset")
        return

### *Slice Column Code Method* `cjs.SliceCol_Code`
The `cjs.SliceCol_Code()` is a supporting method to standardize and normalize the column that contains all the offense codes, allowing for consistency and easy matching when back filling data. It is also an imperative supporter function for analyzing the most serious offenses. This method results in creating a new column called `Code (4)`, stripping any existing leading zeroes and special case handling to extract either the first 3 digits or 4 digits of the code column. Based on the *All_OffenseCodes.csv* file, the crimes involving a homicide are coded from *910* to *998*, but the low-level miscellaneous crimes are coded in the *9,900* to *9,999*. Without specification of which code should be extracted as 3 or 4 digits, the script will miscalculate homicides as low-level offenses. Thus, requiring case handling, which is best solved by using `numpy.select()` method. Lastly, the new column, `Code (4)` will be assigned in memory as the new private variable `_Col_Code`, originally initialized in the constructor.

For free text of *999* (homicide) and *9,999* (other crime), cannot be accounted in terms of specialized case handling, as the script has no way of reading it. Therefore, if there were to be a free text for homicide, it would be normalized as *9,990* if the original dataset contains ending zeros for the code column, causing it to be considered one of the lowest offenses. At this time, this is not too much of a concern, given that free text is rare in the data warehouse.

In [9]:
def SliceCol_Code(self):
    
    """
    Support Method: Extracts and Stardardizes offense codes to its 3 or 4 digit values.
            
    Returns
    ----------
    New Column
        Creates a new column within the pandas.DataFrame() as "Code (4)" column
    """
    
    # Create new column
    newCol_Name = 'Code (4)'
    col_code = self._data[self._Col_Code]
        
    # Standardize codes
    cleaned_codes = col_code.astype(str).fillna('')
    cleaned_codes = cleaned_codes.str.lstrip('0')
        
    # Exception Handling
    prefix_3digit = ('91', '92', '93', '94', '95', '96', '97', '98')
    condition_3digit = cleaned_codes.str.startswith(prefix_3digit)
    choice_3digit = cleaned_codes.str[:3]
    choice_4digit = cleaned_codes.str[:4]
    self._data[newCol_Name] = np.select(
        condlist=[condition_3digit],
        choicelist=[choice_3digit],
        default=choice_4digit
    )
        
    # Re-Assignment of Column Code
    self._data[newCol_Name] = pd.to_numeric(self._data[newCol_Name], errors='coerce')
    self._Col_Code = newCol_Name

### *Fill in Blank Column Method* `cjs.Fill_BlankCol()`
The `cjs.Fill_BlankCol()` function is like a supporter method, except it can be accessed by the user. It is designed to handle null columns regarding the offenses. These columns could be the offense type, name, degree, or general statute. The automatic assumption of this method is to fill in the `_Col_Class`, which is the second most important column that supports the calculator. The design of this function is versatile to any column that is specified, this method must be ran several times if there are several columns that need backfilling. Lastly, it is designed to handle special cases, if necessary. Referring to the [Test_Data.csv](#test_data.csv), `Offence Type Desc` column has partial information where some values represent only the type while others represent the type and degree. The `Value_Exception=` parameter for the `cjs.Fill_BlankCol()` is to keep the values that have the degree in them, while filling in the ones that have no pertinent information. This parameter is not case sensitive to capitalization but is sensitive to spelling. Most importantly, the method needs the *All_OffenseCodes.csv* to be specified, which must be initialized outside of the function.

This method is not meant to standardize or normalize the columns that are ran through, therefore manual cleaning is still necessary after utilization of this module. However, even with an un-normalized column, the calculator will still function error free. Also keep in mind, for any row with missing or invalid codes, these rows will be dropped completely and stored in the `_droppedRows` private variable. While dropping any row may be concerning, many observed datasets that contained null values for the offense code also had null values for the rest of the row. Afterwords, if any rows were dropped, a statement will print how many rows and percentage of the entire dataset were dropped in the process. In terms of the *All_OffenseCodes.csv*, there are duplicate codes due to a change in general statutes. From observation, the last instance of a duplicated code is the most up to date listing and the selected instance that will be utilized for backfilling, while the other previous iterations of such code are dropped.

In [10]:
def Fill_BlankCol(
    self, *,
    File_OffenseCodes: pd.DataFrame,
    File_colNull: Optional[str] = None,
    Data_colNull: Optional[str] = None,
    Value_Exception: Optional[Union[str, List[str]]] = None
):
    
    """
    Backfills missing data pertaining to the Offence Codes dataset provided by NC State.
        
    Parameters
    ----------
    File_OffenseCodes (pandas.DataFrame())
        Specifies the variable containing the Offense Codes in a pandas.DataFrame()
    File_colNull (str) (OPTIONAL)
        The column header in the Offense Codes dataset that contains the needed values
    Data_colNull (str) (OPTIONAL)
        The column header of the 
    Value_Exception (str | list[str]) (OPTIONAL)
                
    Returns
    ----------
    New Column
        Creates and fills a new column containing existing/unaltered data and filling in missing data
    """    
    
    # Column Code (4) Check
    if 'Code (4)' not in self._data.columns:
        self.SliceCol_Code()
            
    # Stripping spaces from Offense_Codes.csv
    File_OffenseCodes = File_OffenseCodes.apply(lambda x: x.astype(str).str.strip())
        
    # File_ColNull Optional Parameter Check: automatic assumption is filling in class column
    if File_colNull is None:
        File_colNull = 'CL'
            
    # Subsetting & Copying specified columns for merge
    lookup_data = File_OffenseCodes[['CODE', File_colNull]].copy()
    lookup_data = lookup_data.drop_duplicates(subset=['CODE'], keep='last')
    lookup_data['CODE'] = pd.to_numeric(lookup_data['CODE'], errors='coerce')
        
    # Data_colNull Optional Parameter Check: automatic assumption is filling in class column
    if Data_colNull is None:
        Data_colNull = self._Col_Class
            
    # Initialzie a new column to be the replacement of old column
    temp_col = f'{self._Col_Class}_original'
        
    # Value_Exception Optional Attribute Check: automatic assumption is there are no exceptions
    if Value_Exception is not None:
        if isinstance(Value_Exception, str):
            exceptions = [Value_Exception.upper()]
        else:
            exceptions = [item.upper() for item in Value_Exception]
        self._data[temp_col] = self._data[temp_col].astype(str).str.upper()
        self._data[temp_col] = self._data[temp_col].replace('', pd.NA)
        self._data.loc[self._data[temp_col].isin(exceptions), temp_col] = pd.NA
        
    # Counting rows before and after null drop
    rows_b4_drop = len(self._data)
    self._droppedRows = self._data[self._data[self._Col_Code].isna()]
    rows_after_drop = self._data.loc[self._data[self._Col_Code].notna()].copy()
    print(f"Dropped {(rows_b4_drop - len(rows_after_drop)) / rows_b4_drop} rows where '{self._Col_Code}' was missing.")
        
    # Merging Offense_Codes with Dataset temporary column
    merged_df = pd.merge(
        rows_after_drop,
        lookup_data,
        left_on=self._Col_Code,
        right_on='CODE',
        how='left'
    )
        
    # Filling in original column nulls with the temporary column
    merged_df[Data_colNull] = merged_df[temp_col].fillna(merged_df[File_colNull])
        
    # Dropping all columns created by Fill_BlankCol method
    merged_df.drop(columns=[temp_col, 'CODE', File_colNull], inplace=True, errors='ignore')
    self._data = merged_df

### *Get Dropped Method* `cjs.Get_Dropped()`
This acts like a checking function where any row(s) that were dropped from the `cjs.Fill_BlankCol()` will be stored in this method. In doing so, it allows for analysts to check what the invalid values within the `_Col_Codes` are. Not that since the original column containing the offense codes will be dropped, a new column name will be assigned with the added "_original" to it. Rows in the `cjs.Calc_HighestOffense()` will not be stored anywhere due to it not being necessary. This is a check function, which will not be needed in most cases, but in the case it is necessary, a demonstration of use will be in Demo 2 and 3 only.

In [11]:
def Get_Dropped(self):
    
    """
    Check Method: Provides data that was dropped from the cjs.Fill_BlankCol() method.
                
    Returns
    ----------
    pandas.DataFrame()
        If dataset was processed by the cjs.Fill_BlankCol() and function dropped columns
    None
        If no columns were dropped
    """
        
    if self._droppedRows is None:
        print("No values were dropped")
    return self._droppedRows

### *Export File Method* `cjs.Export_File()`
This is a supporter method for easy exporting of any file utilized in this python script. The standard is that all files will be exported as a CSV, and the exported file will only be the latest version of it. Within this script, the file will export into the specified folder by the user, based on `Folder_Path=` parameter. However, if no folder path is stated, the file will export to the *Main Page* where the user executes the python module. The name of the exported dataset will have the same name as the original file, with the addition of *Processed* in front of it. Although, if the `cjs.DataSource()` was initialized using a `pandas.DataFrame()` variable, then it's return name will be 'pd_DataFrame'. If needed, the name of the exported file can be changed by filling in the parameter `File_Name=`, but this is optional and has no effects if the parameter is not utilized. Afterwords, a statement will print out the name and file location. In the case that no dataset exist within the `cjs.DataSource()` object, then the respective statement will print and return nothing. Listed below are potential name formatting’s of the file users provide.
- PROCESSED_[Original File Name].csv
- _PROCESSED_[Original File Name].csv
- PROCESSED_[New Fil Name].csv
- _PROCESSED_[New File Name].csv
- PROCESSED_pd_DataFrame.csv
- _PROCESSED_pd_DataFrame.csv

**Note:** necessary folder formatting of folder names needs to be known prior to execution.
- ..[Folder Name]/ -> folder is nested outside of folder which python script is running
- [Folder Name]/ -> folder is nested inside of folder which python script is running

In [12]:
def Export_File(
    self, 
    Folder_Path: Optional[str] = None, 
    File_Name: Optional[str] = None
):

    """
    Exports processed dataset to a CSV file format.
            
    Parameters
    ----------
    Folder_Path (str) (OPTIONAL)
        Specifies the folder in which file should be exported too
    File_Name (str) (OPTIONAL)
        Specifies name of processed dataset, default is the PROCESSED_[Original Dataset Name]
                
    Returns
    ----------
    CSV UTF-8
        CSV file that is comma deliminated
    """

    # Version Check
    if self._newData is not None:
        df_to_export = self._newData
    elif self._data is not None: 
        df_to_export = self._data
    else: 
        print("No data exist in cjs.DataSource() object")
        return
    
    # File Name Check or Name Extraction
    if File_Name is None:
        if isinstance(self._CSV_File, str):
            folder, file_path = self._CSV_File.rsplit('/', 1)
            File_Name = file_path.rsplit('.', 1)[0]
        else:
            File_Name = 'pd_DataFrame'
    
    # Drop rows where only all values are missing
    df_to_export = df_to_export.dropna(how='all')
    
    # Separation of original file and exported file
    df_to_export = df_to_export.copy()
        
    # Replacing null value representation
    df_to_export = df_to_export.replace(np.nan, '')
        
    # Standardizing all values to str for easy Excel file reading
    df_to_export = df_to_export.astype(str)
        
    # Folder_Path Attribute Check & Format Check
    if Folder_Path is None:
        Folder_Path = '_'
    elif Folder_Path is not None:
        if Folder_Path[-1] != '/':
            Folder_Path = Folder_Path + '/'
    
    # Export File
    df_to_export.to_csv(
        f"{Folder_Path}PROCESSED_{File_Name}.csv", 
        index=False, 
        encoding='utf-8'
    )
    
    # Print Statement of File Name and Location
    if Folder_Path == '_':
        print(f'Exported as "{Folder_Path}PROCESSED_{File_Name}.csv"')
        return print()
    print(f'Exported in "{Folder_Path}" folder as "PROCESSED_{File_Name}.csv"')
    return print()

### *Calculate Highest Offense Method* `cjs.Calc_HighestOffense()`
The main function of this module is the `cjs.Calc_HighestOffense()`, which groups the dataset based off of a specific column specified in the `Group_By` parameter. Common columns to group by could be by person ID, case number, or booking ID. If there is no specification for how the offenses should be grouped, the automatic assumption is based on the `_Col_PrimKey` constructor attribute. Although, if a column other than the primary key is to be the main grouper or if the primary key was never written in the constructor, the `Group_By=` attribute must be stated. If no parameter is given, the method will print an error message informing of issues. The calculator first standardizes the codes in the given dataset, extracts all predicted classes to the highest or based on `Find_Class=` param, then groups the offenses, and lastly returns the most serious offenses into a new variable. The ordering of how tie breakers work is **(1)** Class, **(2)** Code, **(3)** first iteration. This being that NC Courts made the class be the main distinction of offense serious, then correlating the code as the other distinction, which is based on lowest values being the most serious. The `Find_Class=` parameter, allows for users to find the highest crime of a specific class. This parameter is not case sensitive allowing for upper or lowercase initialization. With this, any 'Blank', '??', or null values for the degree type will be filtered out. This is because the information provided in the *All_OffenseCodes.csv* still has missing data other than the offense codes. This issue will mostly occur within Traffic and Infraction cases. When utilizing `cjs.Calc_HighestOffense()` method, the aggregated data will be nested into the `_newData` variable. This is both common practice, and the best method in securing the original data, without deleting any rows. Easy extraction of either original or aggregated data can be processed through the `cjs.Get_Data()` function.

**Important:** Prior to data pull in MSSQL, raw data must be used for calculator to work accurately. This is because this method finds specified values in the `Class_Order` variable and has a specialized case handling tailored to the MSSQL data pulls. If data warehouse were to change, this line would need to be updated: `s = re.sub(r'FELONY|MISDEMEANOR|CLASS|W/G', '', s)`

In [13]:
def Calc_HighestOffense(
    self, *,
    Group_By: Optional[Union[str, List[str]]] = None, 
    Find_Class: Optional[Union[str, List[str]]] = None
):
    """
    Calculates the highest offense within the given parameter(s),
    Sorting order: class, code
            
    Parameters
    ----------
    Group_By (str) (REQUIRED | OPTIONAL)
        Specifies the method in which grouping should be processed by, 
        *Optional* and defaulted to _Col_PrimKey if initially specified,
        *Required* if _Col_Primkey is not initially specified
    Find_Class (str) (OPTIONAL)
        Specifies is a certain class/degree needs to be extracted,
        default is the highest class of given parameter
             
    Returns
    ----------
    pandas.DataFrame()
        An extracted dataset of the most serious offenses (given its parameter) 
        within the dataset provided, and assigned to the _newData local variable
    """
    # Column Code (4) Check
    if 'Code (4)' not in self._data.columns:
        self.SliceCol_Code()
                
    # Group_By parameter check
    if Group_By is None:
        if hasattr(self, '_Col_PrimKey') and self._Col_PrimKey is not None:
            Group_By = self._Col_PrimKey
        else:
            print("Group_By parameter needs to be filled or _Col_PrimKey needs to be filled.")
            return
    
    # Standardize Group_By parameter to list
    group_list = [Group_By] if isinstance(Group_By, str) else Group_By
        
    # Find_Class parameter check & list standardization
    class_targets = None
    if Find_Class is not None:
        class_targets = [fc.upper().strip() for fc in ([Find_Class] if isinstance(Find_Class, str) else Find_Class)]
        
    # Creating a set of valid class's based on given class_order & order columns in that perspective
    valid_class_set = set(self.class_order).difference({'??', ''})  
    sorted_classes = sorted(list(valid_class_set), key=len, reverse=True)
        
    # Specialized character extraction for class columns containing several predicted class values
    def extract_class_components(class_string):
        """(1) Pulls the highest predicted class value or 
        (2) the matching Find_Class value of all predicted values"""
        
        # Checking if value of the Col_Class is valid, will return "??", "Blank", and null values as empty strings
        if pd.isna(class_string):
            return ''
        
        # Converting all strings to uppercase allowing for non-case sensitive Find_Class typology
        s = str(class_string).upper()
    
        # Clean & merge re-occuring values not useful to the class column
        s = re.sub(r'FELONY|MISDEMEANOR|CLASS|W/G', '', s) 
            
        # Iterative extraction looping through the merged string looking for matching values
        extracted_components = []
        s_working = s
        i = 0
        while i < len(s_working):
            matched = False
                
            # Check for the first character of each code first (ex. B -> B1)
            for cls in sorted_classes:
                if s_working.startswith(cls, i):
                    extracted_components.append(cls)
                    i += len(cls)
                    matched = True
                    break
                
            # Check for the separator '/'
            if not matched and s_working[i] == '/':
                extracted_components.append('/')
                i += 1
                matched = True
            
            # Check for actual match
            if not matched:
                i += 1
        
        # Returning results if there is a match or 
        result = ''.join(extracted_components).strip('/')
        return result

    # Copy and Prep new data variable
    df = self._data.copy()
    df["_orig_order"] = range(len(df))   
    df['_clean_class'] = df[self._Col_Class].apply(extract_class_components)
    
    # Base rank cummulation
    MAX_RANK_VALUE = len(self.class_order)
    best_target_rank = MAX_RANK_VALUE
    if class_targets:
        target_ranks = [self.class_rank.get(cls, MAX_RANK_VALUE) for cls in class_targets]
        best_target_rank = min(target_ranks)

    # Map classes to numerical ordering
    df['base_rank'] = df['_clean_class'].map(self.class_rank)
    composite_mask = df['_clean_class'].str.contains('/', na=False)
    df_composite = df[composite_mask].copy()
    
    # Split any value containing "/"
    if not df_composite.empty:
        df_exploded = df_composite.assign(
            component_class=df_composite['_clean_class'].str.split('/') 
        ).explode('component_class')
        df_exploded['component_class'] = df_exploded['component_class'].str.strip()
        df_exploded['comp_rank'] = df_exploded['component_class'].map(self.class_rank)

        # Select classes based on Find_Class parameter
        if class_targets:
            df_exploded = df_exploded[
                df_exploded['comp_rank'] >= best_target_rank 
            ].copy()

        # Same class tie breaker, find smallest/ most serious code of the offenses with the same class value
        min_ranks = df_exploded.dropna(subset=['comp_rank']).groupby(level=0)['comp_rank'].min()
        df.loc[min_ranks.index, 'base_rank'] = min_ranks
    
    # Filling in all empty class values as the maximum ranking to not exclude missing information from calculations
    df['base_rank'] = df['base_rank'].fillna(MAX_RANK_VALUE).astype(np.int64) 
        
    # Create new variable for dataframe that is cleaner to work with
    df_filtered = df.copy() 
    
    # Pattern recognition, finding targeted class based on Find_Class parameter
    if class_targets:
        patterns = [r'\b' + re.escape(target) + r'\b' for target in class_targets]
        combined_pattern = '|'.join(patterns)
        mask = df_filtered['_clean_class'].str.contains(combined_pattern, na=False, regex=True)
        df_filtered = df_filtered[mask].copy()

        # Error statement if no classes are found from parameter
        if df_filtered.empty:
            self._newData = None
            print(f"No offenses found containing the specified Find_Class target(s): {', '.join(class_targets)}")
            return
        
    # Sort & extract the highest offense per Group_By parameter or Col_PrimKey attribute
    df_filtered = df_filtered[df_filtered['base_rank'] != MAX_RANK_VALUE].copy()
    
    # Error check
    if df_filtered.empty:
        self._newData = None
        print("No valid offenses remain after filtering and rank verification.")
        return

    # Prevent data point exclusion with missing codes
    MAX_CODE_VALUE = 9999 
    df_filtered['sort_code'] = df_filtered[self._Col_Code].astype(float).fillna(MAX_CODE_VALUE)
    
    # Sorting function based on 
    # (1st) Class, (2nd) Code, (3rd) first iteration if containing counts of a singular charge
    df_filtered = df_filtered.sort_values(
        by=["base_rank", "sort_code", "_orig_order"],
        ascending=[True, True, True] 
    )
    
    # Ordered grouping function allowing for smooth calculating with several columns
    indexes_minCode = df_filtered.groupby(group_list).head(1).index
    newData = df_filtered.loc[indexes_minCode].copy()
    
    # Drop all supporting columns unnecessary to data
    col_to_drop = ['base_rank', '_orig_order', 'sort_code', '_clean_class']
    newData = newData.drop(
        columns=col_to_drop, 
        errors='ignore'
    ) 
    
    # Return the calculated data to a new variable and maintain original dataset in the _data variable
    self._newData = newData

## **Input Data**

### *All_OffenseCodes.csv*
Starting with the `offense_codes` data, this document is provided by the [NC Courts](https://www.nccourts.gov/documents/publications/nc-courts-offense-codes-and-classes) containing all the current abbreviations, offenses, and their codes. Without modification, this document cannot be utilized in the calculator, as missing data needs to be addressed prior to python script execution. The missing data is referring to the `CL` column, where the classes of certain offenses are labeled as '??' or is a blank value. With the missing values, the calculator excludes these variables, leading to a high potential of miscalculation in data extraction. With the complexity of sentencing, a high number of offenses have several class outcomes, depending on the stipulation of the person and their alleged crime. In this demonstration, all missing or '??' values in the `CL` column were filled in manually based on their general statutes. The improved offense codes results in any 'place holder charge' or blank charges to have several classes as their class description. In doing this, it accounts for all possibilities of offense class and prevents over exclusion of rows when needing to find the highest offense of a specified class. The formatting of the new offense code's file is demonstrated below with murder charges. Below are variations of the class column. There are still 'Blank' values due to there not being any class stipulation in the general statute, or there being no statute found. 

**Note**: Without an improved version of the offense codes, any version of the highest offense calculator will exclude missing, 'Blank', and '??' values. This being the root cause of the miscalculation when trying to find the highest offense in a specified class.

In [14]:
import pandas as pd
offense_codes = pd.read_csv('TestCSV_FilesInput/Test_OffenseCodes.csv')
file_rExample_rException = offense_codes.iloc[[0, 9, 23, 30]][['CODE', 'Offense Description', 'CL']]
file_rExample_rException

    CODE            Offense Description       CL
0    910      MURDER OF AN UNBORN CHILD        A
9    930                         MURDER  A/B1/B2
23   955  SOLICITATION TO COMMIT MURDER    Blank
30   999           HOMICIDE - FREE TEXT       ??

### *Test_Data.csv*
For the demonstration, the `test_data` is an old query performed in data warehouse. This spreadsheet illustrates the key components and randomness of datasets created from the warehouse. Often, most of the information related to the offense is missing, which includes the offense description, type, and degree. For the calculator to execute with the highest accuracy, prior data observation is necessary. Below is a sample set of columns to observe. Notice how `Offence Type Desc` has inconsistent values. Some values in the `Offence Type Desc` are the type and class, others are only the type, and many have null values. At the same time, the `Offense Desc` and `Offense Degree Desc` is completely null. This is very important observation when choosing which column is best fit for the `_Col_Class` attribute in the constructor.

In [15]:
test_data = pd.read_csv('TestCSV_FilesInput/Test4_CY21-CY24 Jail Data DRAFT.csv')
file_rExample = test_data.iloc[
    [0, 7, 1102, 135, 51, 8, 83]][
    ['Offence Code', 'Offence Type Desc', 'Offense Desc', 'Offense Degree Desc', 'Case Info Num', ]]
file_rExample

,Offence Code,Offence Type Desc,Offense Desc,Offense Degree Desc,Case Info Num
0,385500.0,NaN,NaN,NaN,17CVD361
7,540500.0,TRAFFIC,NaN,NaN,21CR200047
1102,444000.0,INFRACTION,NaN,NaN,20CR700184
135,102000.0,FELONY,NaN,NaN,20CR219417
51,291200.0,MISDEMEANOR,NaN,NaN,21CR200076
8,220500.0,FELONY - CLASS H,NaN,NaN,20CRS015059
83,133600.0,MISDEMEANOR - CLASS 1,NaN,NaN,13CR237218

## **Demonstration**
In this section, there will three different walk-throughs consisting of a simple version and an in detailed version of how to utilize the `cjs.DataSource()` library.

### **Demo 1: Simplistic Code Review**
This is a more simplistic version of how the code should look if doing a simple execution of finding the highest crime including only class A results. The test data will be referred to as `test4_data`.

In [16]:
# Imports
import pandas as pd
import CJ_Services as cjs

# Initialize
all_offense = pd.read_csv('TestCSV_FilesInput/Test_OffenseCodes.csv')
test5_data = cjs.DataSource(
    CSV_File='TestCSV_FilesInput/Test4_CY21-CY24 Jail Data DRAFT.csv',
    Col_Class='Offence Type Desc',
    Col_Code='Offence Code'
)

# Fill in offense class (Optional fill in other columns)
test5_data.Fill_BlankCol(
    File_OffenseCodes=all_offense,
    Value_Exception=['felony', 'misdemeanor', 'traffic', 'infraction']
)

# Calculate highest offense with results of class A
test5_data.Calc_HighestOffense(
    Group_By='Case Info Num',
    Find_Class='A'
)

# Export CSV
test5_data.Export_File(
    Folder_Path='TestCSV_FilesOutput/',
    File_Name='test5'
)

Dropped 11.19% rows where 'Code (4)' was missing.
Exported in "TestCSV_FilesOutput/" folder as "PROCESSED_test5.csv"

### **Demo 2: Detailed Walk-Through**
For this demonstration, two variables of the same data will be used to display the different format alternatives. These variables will be called `test1_data`, `test2_data`, and `test3_data`

##### **1.** Specified libraries must be imported to your *File.py* or *File.ipynb*. These imports are *Pandas* library and the personal *CJ_Services* library. As written below, libraries can be imported as personal phrases, however, standard practice is to use their abbreviation.

In [17]:
import pandas as pd
import CJ_Services as cjs

##### **2.** Initializing *All_OffenseCodes.csv* file. This will be done using the `pd.read_csv()` method.

In [18]:
all_offense = pd.read_csv('TestCSV_FilesInput/Test_OffenseCodes.csv')

##### **3.** Initializing the *Test1_CY21-CY24 Jail Data DRAFT.csv* file. This spreadsheet will utilize the newly created class and initiated like this, `cjs.DataSource()`. Keep in mind that each attribute required or optional must be written and equaled to their perspective values. Python is case sensitive to indentions, but other formatting is personal preference and below is standard practice. <u>Note</u> that users must be aware spelling errors may occur when specifying each column, as this portion of the code is case sensitive.

In [19]:
# Option 1: w/ PrimKey
test1_data = cjs.DataSource(
    CSV_File='TestCSV_FilesInput/Test1_CY21-CY24 Jail Data DRAFT.csv',
    Col_PrimKey='Case Info Num',
    Col_Class='Offence Type Desc',
    Col_Code='Offence Code'
)
# Option 2: w/out PrimKey
test2_data = cjs.DataSource(
    CSV_File='TestCSV_FilesInput/Test2_CY21-CY24 Jail Data DRAFT.csv',
    Col_Class='Offence Type Desc',
    Col_Code='Offence Code'
)

# Option 3: w/ pd.DataFrame() file
test3 = pd.read_csv('TestCSV_FilesInput/Test3_CY21-CY24 Jail Data DRAFT.csv')
test3_data = cjs.DataSource(
    CSV_File=test3,
    Col_Class='Offence Type Desc',
    Col_Code='Offence Code'
)

##### **4A.** As stated before, the `Offence Type Desc` has a variety of values that contain an offense degree and ones that don't. This means prior to using the `cjs.Fill_BlankCol()` method, the `Value_Exception` parameter has to be utilized to prevent the unwanted values to override the method. This argument must be a singular string or a list of strings, it also can be written in the parameter or outside of it, dependent on number of exception cases. Stated prior, the `Value_Exception` argument is not case sensitive. Also, the automatic assumption is that the function is filling in the dataset's offense classes if no other parameters are written.

In [20]:
# Option 1: Exception outside of method
exceptions = ['felony', 'MISDEMEANOR']
test1_data.Fill_BlankCol(
    File_OffenseCodes=all_offense,
    Value_Exception=exceptions
)

# Option 2: Exception inside the method
test2_data.Fill_BlankCol(
    File_OffenseCodes=all_offense,
    Value_Exception=['FELONY', 'MISDEMEANOR']
)

# Option 3: Fill specifying column names, not necessary for Class Column
test3_data.Fill_BlankCol(
    File_OffenseCodes=all_offense, 
    File_colNull='Offense Description',
    Data_colNull='Offense Desc',
    Value_Exception=['Felony', 'Misdemeanor', 'Infraction', 'Traffick']
)

Dropped 11.19% rows where 'Code (4)' was missing.
Dropped 11.19% rows where 'Code (4)' was missing.
Dropped 11.19% rows where 'Code (4)' was missing.

##### **4B.** The second portion of this function is calling another function to look at all the dropped data. Again, this is to check if there are issues with the `cjs.Fill_BlankCol()` and it dropping the wrong values. The main idea of this is that if there is a high percentage of dropped data, then it is necessary to verfiy that the data being dropped is due to the fact that `_Col_Code` values are missing or invalid. <u>Note</u> that users must assign a variable to calling the method, in order to view dropped rows in a dataset.

In [21]:
test2_dropped = test2_data.Get_Dropped()
test2_dropped.head()

,PID Num,Last Name,First Name,Booking Id,JID,Booking Begin Date,Booking End Date,Offence Code,Statute Code,Offence Type Desc_original,...,BAIL DETAILS BOND TYPE,OFF CHARGES ACTUAL BAIL AMOUNT,ORDERS BOND TYPE,ORDERS RECOM BAIL AMOUNT,ORDERS ACTUAL BAIL AMOUNT,Order Id,Case Info Num,Order Sub Type,Status Reason,Code (4)
4,359215.0,GILL,FENTA,2472775,21-000014,2021-01-01,2021-01-01,NaN,nan,NAN,...,nan,NaN,nan,NaN,NaN,4083062.0,HLD-169813,CMPDEM,REL-UNS,NaN
18,383183.0,LITTLE,MICHAEL,2472779,21-000018,2021-01-01,2021-02-03,NaN,nan,NAN,...,nan,NaN,nan,NaN,NaN,4085321.0,HLD-170092,1099,TRN-OJ,NaN
37,409263.0,JOHNSON,ANTONIO,2472763,21-000002,2021-01-01,2021-01-05,NaN,nan,NAN,...,nan,NaN,nan,NaN,NaN,4083015.0,HLD-169810,CMPDEM,REL-BOND,NaN
42,442502.0,COLLIER,QAWAL,2472781,21-000020,2021-01-01,nan,NaN,nan,NAN,...,nan,NaN,nan,NaN,NaN,4083104.0,HLD-169815,1099,ADM-ADMN,NaN
49,451769.0,WATTS,QUENTAVIOUS,2472772,21-000011,2021-01-01,2021-01-05,NaN,nan,NAN,...,nan,NaN,nan,NaN,NaN,4083218.0,HLD-169821,1099,REL-BOND,NaN

##### **4C.** The after checking the drooped data for any irregularity, utilizing the previous function, it can fill in any column related to offense. For these datasets, the offense description is missing. Due to this, all permanent operations must be stated prior to non-permanent operations. The only non-permanent operation currently is the calculator method. Below is a demonstration of how users were to fill in other null columns. When performing `cjs.Fill_BlankCol()` method several times, the automatic drop text will continue to inform how many more rows have been dropped. <u>Note</u> that the second time around, the rows dropped is zero because the function had already been ran, dropping all the NULL rows in the first time around. So any future attempts of `cjs.Fill_BlankCol()` will state zero as the number of rows dropped.

In [22]:
test2_data.Fill_BlankCol(
    File_OffenseCodes=all_offense,
    File_colNull='Offense Description',
    Data_colNull='Offense Desc'
)

Dropped 22.39% rows where 'Code (4)' was missing.

##### **5A.** After making sure all the offense degrees are accounted for, users can use the `cjs.Calc_HighestOffense()` method. The `test4_data` will demonstrate finding the highest offense of the entire dataset, grouped by the primary key, which is case number. On the other hand, `test5_data` will demonstrate calculating the highest offense of a specific class. Since this data was not initialized with a primary key column, users will have to specify how to group the data. For comparison, the case number will be the grouping metric. <u>Note</u> that option 2B and 2C demonstrate the variablility of how to format the optional parameters.

In [23]:
# Option 1: no attribute declaration
test1_data.Calc_HighestOffense()

# Option 2A: 1 param for either group_by or find_class
test2_data.Calc_HighestOffense(
    Group_By='Case Info Num', 
    Find_Class='c')

# Option 2B: Several params
classes = ['a', 'b1', 'b2', 'c']
test3_data.Calc_HighestOffense(
    Find_Class=classes
)

# Option 2C: Several params
test1_data.Calc_HighestOffense(
    Find_Class=['A1', '1', '2']
)

Group_By parameter needs to be filled or _Col_PrimKey needs to be filled.

##### **5B**. To view or do more operations in python, the `cjs.Get_Data()` method will have to be used as follows. This method allows for specification of pre- or post-data, based on if users utilized a non-permanent operation. In the *Option 1* is a prime example of how it will return the calculated data, stated as the first line of the output. This is because in the previous step, *5A*, the `cjs.Calc_HighestOffense()` had been initiated initializing the `_newData` variable in the constructor. To pull the original data without specifying, it'll only work if a non-permanent method has not been initialized.

In [24]:
# --- Calculated Data ---
# Option 1: no parameter specification
test2_calc = test2_data.Get_Data()

# Option 2: parameter specified
test2_calc = test2_data.Get_Data('calculated data')

# --- Original Data ---
# Option 3: no parameter specification and no data in the _newData variable
test3_orig = test3_data.Get_Data()

# Option 4: parameter specified
test3_orig = test3_data.Get_Data('original data')

# --- No Dataset Return --- 
# Option 5: no data in the _newData variable
test3_none = test3_data.Get_Data('calculated data')

Returning Calculated Data
Returning Calculated Data
Returning Original Data
Returning Original Data
Data has not been calculated

##### **6.** Lastly, after all operations have been completed to user needs, the `pandas.DataFrame()` or `cjs.DataSource` can be exported. If the dataset was initialized into a new variable, like in step 5B, export will need to be manual using `pandas.to_csv()`. If done this way, there will not be a printed out statement of where the file is. Otherwise, the dataset is still it's original `DataSource` type and can be exported using `cjs.Export_File()` method. This method does have an attribute where users can input a folder to where they would like their CSV file to be. Make sure you thoroughly understand how to format the string for `Folder_Path=` as it is different based on the type of file python code is executing and the location of folder relative to the file. To prevent confusion, a statement will print out as to where the file is, if folder is specified, and what the file name is. If folder is not specified, automatic assumption must be that file is in the same folder as the python script. <u>Note</u> that Option 4 does not have a print statement of where and what the file name is due to the fact that users have to manually write in code where the file goes. Rather than the `cjs.Export_File()` function which were in Option 1, the execution does not require to write a path.

In [25]:
# Option 1: no parameter specification
test1_data.Export_File()

# Option 2: parameter specified
test2_data.Export_File(Folder_Path='TestCSV_FilesOutput')

# Option 3: w/ file name
test3_data.Export_File(
    Folder_Path='TestCSV_FilesOutput/',
    File_Name='test3'
)

# Option 4: pandas.DataFrame() method, if dataset is no longer a DataSource type
test2_calc.to_csv(
    f"TestCSV_FilesOutput/PROCESSED_Test5_CY21-CY24 Jail Data Draft.csv", 
    index=False, 
    encoding='utf-8'
)

Exported as "_PROCESSED_Test1_CY21-CY24 Jail Data DRAFT.csv"

Exported in "TestCSV_FilesOutput/" folder as "PROCESSED_Test2_CY21-CY24 Jail Data DRAFT.csv"

Exported in "TestCSV_FilesOutput/" folder as "PROCESSED_test3.csv"

### **Demo 3: Specialized Case Handling**
With this demonstration, it is showcasing how the calculator sorts and extracts the highest offense given the testing parameters. This manipulated setup specifically only tests the `Find_Class` parameter.

#### **ManipulatedSetup.csv**
This is the general setup that will be used to demonstrate the different options with the `cjs.Calc_HighestOffense()` method. This table contains these columns: Test #, Case Number, Offense Class, Offense Description, Outcome T/F, Parameter Test, and Notes. The 'Outcome T/F' will be the most important as these test were hand picked verify the correct outcome. Please refer to original file to read what each test is testing. In terms of 'Class' column, these values will be partially missing and value replacement as its first formal testing. Also, as a side note, the the calculator only calculates over the original data, therefore there would be no need to re-initialize the data.

In [26]:
import pandas as pd
import CJ_Services as cjs

codes = pd.read_csv('TestCSV_FilesInput/Test_OffenseCodes.csv')

data = cjs.DataSource(
    CSV_File='TestCSV_FilesInput/ManipulatedSetup.csv',
    Col_PrimKey='Case Number',
    Col_Code='Offense Code',
    Col_Class='Offense Class'
)

data.Fill_BlankCol(
    File_OffenseCodes=codes,
    Value_Exception=['Felony', 'Misdemeanor', '??', 'Blank', 'nan']
)

data.Fill_BlankCol(
    File_OffenseCodes=codes,
    Data_colNull='Offense Desc',
    File_colNull='Offense Description'
)

data_get = data.Get_Data()
data_get[['Test #', 'Case Number', 'Offense Code', 'Offense Class', 'Outcome T/F']]

Dropped 0.00% rows where 'Code (4)' was missing.
Dropped 0.00% rows where 'Code (4)' was missing.
Returning Original Data

    Test # Case Number  Offense Code        Offense Class  Outcome T/F
0        1  00CR000001           930              A/B1/B2         True
1        1  00CR000001           950              A/B1/B2        False
2        2  00CR000002           930              A/B1/B2         True
3        2  00CR000002          1170  B1/B2/C/D/E/F/G/H/I        False
4        3  00CR000003          1377                F/G/H         True
5        3  00CR000003          2320                  H/1        False
6        4  00CR000004          1306              C/E/F/H         True
7        4  00CR000004          1348                    C        False
8        5  00CR000005          1153                    C         True
9        5  00CR000005          1306              C/E/F/H        False
10       6  00CR000006          1127                   B2         True
11       6  00CR000006          1023                    F        False
12       7  00CR000007          1127          FELONY - B2         True
13       7  00CR000007          1023                    F        False
14       8  00CR000008           923                   B2         True
15       8  00CR000008           930              A/B1/B2        False
16       9  00CR000009           910                    A        False
17       9  00CR000009          5714                 A1/1        False
18      10  00CR000010           921                    C         True
19      10  00CR000010           915                    D        False
20      11  00CR000011           921                    C         True
21      11  00CR000011          1020                  C/E        False
22      12  00CR000012          1032                  D/F         True
23      12  00CR000012          1102                    D        False

#### **Test Rows 1-7** Find_Class=None
**(1)** With the presence of only 'predicted' classes, will it extract the highest predicted case? If so and if both are the same, will it extract the lowest code?

**(2)** With the presence of only 'predicted' classes, will it extract the highest predicted case? If so and if both are different, will it extract the more serious class?

**(3)** With the presence of only 'predicted' classes, will it extract the highest predicted case? If so, if both are different, and not 'A' class, will it extract the more serious class?

**(4)** With the presence of 'predicted' and solid class, will it extract the highest case? If so and both are the same class, will it choose the more serious code?

**(5)** With the presence of 'predicted' and solid class, will it extract the highest case? If so and both are the same class, will it choose the more serious code?

**(6)** With solid classes, will the predicted seriousness of codes be overridden by class order?

**(7)** With impartial data, will the predicted seriousness of codes be overridden by class order?

In [27]:
data.Calc_HighestOffense()

data_get = data.Get_Data()
data_get['Test #'] = pd.to_numeric(data_get['Test #'], errors='coerce')
data_show = data_get[
    data_get['Test #'] <= 7
].sort_values(by='Test #')
data_show[['Test #', 'Case Number', 'Offense Code', 'Offense Class', 'Outcome T/F']]

Returning Calculated Data

    Test # Case Number  Offense Code Offense Class  Outcome T/F
0        1  00CR000001           930       A/B1/B2         True
2        2  00CR000002           930       A/B1/B2         True
4        3  00CR000003          1377         F/G/H         True
6        4  00CR000004          1306       C/E/F/H         True
8        5  00CR000005          1153             C         True
10       6  00CR000006          1127            B2         True
12       7  00CR000007          1127   FELONY - B2         True

#### **Test Rows 8-9** Find_Class='B2'
**(8)** With the presence of 'predicted' and solid classes, will it extract the predicted case wanted? If so, if both are the same, will it extract the lowest code?

**(9)** With the presence of 'predicted' and solid classes, will it exclude the values unwanted in the search? This test should fail therefore only test 8 result should remain

In [28]:
data.Calc_HighestOffense(
    Find_Class='B2'
)

data_get = data.Get_Data()
data_get['Test #'] = pd.to_numeric(data_get['Test #'], errors='coerce')
data_show = data_get[
    (data_get['Test #'] == 8) |
    (data_get['Test #'] == 9)
].sort_values(by='Test #')
data_show[['Test #', 'Case Number', 'Offense Code', 'Offense Class', 'Outcome T/F']]

Returning Calculated Data

    Test # Case Number  Offense Code Offense Class  Outcome T/F
14       8  00CR000008           923            B2         True

#### **Test Rows 10-12** Find_Class = ['C', 'D']

**(10)** With the presence of solid classes and list of Find_Class parameters. Will it recognize both values and select the highest class.

**(11)** With the presence of 'predicted' and solid classes, and a list of Find_Class parameters. Will it recognize both values that are the same and select the more serious code.

**(12)** With the presence of 'predicted' and solid classes, and a list of Find_Class parameters. Will it recognize both values that are the same and select the more serious code.

In [29]:
data.Calc_HighestOffense(
    Find_Class=['C', 'D']
)

data_get = data.Get_Data()
data_get['Test #'] = pd.to_numeric(data_get['Test #'], errors='coerce')
data_show = data_get[
    data_get['Test #'] >= 10
].sort_values(by='Test #')
data_show[['Test #', 'Case Number', 'Offense Code', 'Offense Class', 'Outcome T/F']]

Returning Calculated Data

    Test # Case Number  Offense Code Offense Class  Outcome T/F
18      10  00CR000010           921             C         True
20      11  00CR000011           921             C         True
22      12  00CR000012          1032           D/F         True

### **Demo 4: Results Comparison**
To better understand the calculator, below is a results comparison of before and after each method once it has been run. The testing data variable will be referred to as `test5_data`. In this results comparison, traffic and infraction keywords will be put as part of the `Value_Exception=` cases. When viewing the results, know that not all traffic and infraction cases have a class description or an offense description, leading to NULL value appearance. In this dataset, `nan` means missing values in python.

##### *View Initialized Data*

In [58]:
# Initialize
test5_data = cjs.DataSource(
    CSV_File='TestCSV_FilesInput/Test4_CY21-CY24 Jail Data DRAFT.csv',
    Col_Class='Offence Type Desc',
    Col_Code='Offence Code'
)
test5_orig = test5_data.Get_Data()
test5_sub = test5_orig[['Offence Code', 'Offence Type Desc', 'Offense Desc']].head(10)
test5_sub

Returning Original Data

   Offence Code Offence Type Desc Offense Desc
0      385500.0               nan          nan
1      132500.0               nan          nan
2      236500.0               nan          nan
3      232100.0               nan          nan
4           NaN               nan          nan
5      102800.0               nan          nan
6      138900.0               nan          nan
7      540500.0           TRAFFIC          nan
8      220500.0  FELONY - CLASS H          nan
9      132300.0               nan          nan

##### *View Backfilled Data*

In [59]:
# --- Test 5: Backfilled Class ---
test5_data.Fill_BlankCol(
    File_OffenseCodes=all_offense,
    Value_Exception=['felony', 'misdemeanor', 'traffic', 'infraction', 'nan']
)
test5_orig = test5_data.Get_Data()
test5_sub = test5_orig[['Code (4)', 'Offence Type Desc', 'Offense Desc']].head(10)
test5_sub

Dropped 11.19% rows where 'Code (4)' was missing.
Returning Original Data

   Code (4) Offence Type Desc Offense Desc
0    3855.0               1/2          nan
1    1325.0                 F          nan
2    2365.0                 I          nan
3    2321.0                 H          nan
4    1028.0                 E          nan
5    1389.0                A1          nan
6    5405.0                            nan
7    2205.0  FELONY - CLASS H          nan
8    1323.0                 H          nan
9    5310.0                 2          nan

In [60]:
# --- Test 5 Backfilled Description ---
test5_data.Fill_BlankCol(
    File_OffenseCodes=all_offense,
    File_colNull='Offense Description',
    Data_colNull='Offense Desc',
    Value_Exception='nan'
)
test5_orig = test5_data.Get_Data()
test5_sub = test5_orig[['Code (4)', 'Offence Type Desc', 'Offense Desc']].head(10)
test5_sub

Dropped 22.39% rows where 'Code (4)' was missing.
Returning Original Data

   Code (4) Offence Type Desc                   Offense Desc
0    3855.0               1/2               NONSUPPORT CHILD
1    1325.0                 F  ASSAULT SERIOUS BODILY INJURY
2    2365.0                 I    CONSPIRE COMMIT FEL LARCENY
3    2321.0                 H                 FELONY LARCENY
4    1028.0                 E       SECOND DEGREE KIDNAPPING
5    1389.0                A1            ASSAULT ON A FEMALE
6    5405.0                           DRIVING WHILE IMPAIRED
7    2205.0  FELONY - CLASS H   BREAK/ENTER TERRORIZE/INJURE
8    1323.0                 H       ASSAULT BY STRANGULATION
9    5310.0                 2       RESISTING PUBLIC OFFICER

##### *View Dropped Data*

In [61]:
# --- Test 5 Check Dropped Data ---
test5_drop = test5_data.Get_Dropped()
test5_sub = test5_drop[['Code (4)', 'Offence Type Desc_original', 'Offense Desc']].head(10)
test5_sub

     Code (4) Offence Type Desc_original Offense Desc
4         NaN                       <NA>          nan
18        NaN                       <NA>          nan
37        NaN                       <NA>          nan
42        NaN                       <NA>          nan
49        NaN                       <NA>          nan
55        NaN                       <NA>          nan
63        NaN                       <NA>          nan
64        NaN                       <NA>          nan
96        NaN                       <NA>          nan
109       NaN                       <NA>          nan

##### *View Calculated Highest Offense*

In [62]:
# --- Test 5: Calculate Highest Offense ---
test5_data.Calc_HighestOffense(
    Group_By='Case Info Num'
)
test5_orig = test5_data.Get_Data()
test5_sub = test5_orig[['Offence Code', 'Code (4)', 'Offence Type Desc', 'Offense Desc']].head(10)
test5_sub

Returning Calculated Data

      Offence Code  Code (4) Offence Type Desc Offense Desc
140        93000.0     930.0           A/B1/B2       MURDER
178        93000.0     930.0           A/B1/B2       MURDER
367        93000.0     930.0           A/B1/B2       MURDER
478        93000.0     930.0           A/B1/B2       MURDER
2269       93000.0     930.0           A/B1/B2       MURDER
2390       93000.0     930.0           A/B1/B2       MURDER
2458       93000.0     930.0           A/B1/B2       MURDER
2472       93000.0     930.0           A/B1/B2       MURDER
2583       93000.0     930.0           A/B1/B2       MURDER
5923       93000.0     930.0           A/B1/B2       MURDER

##### *A : View Calculated Offense*

In [63]:
# --- Test 5: Calculate Highest Offense by Class A ---
test5_data.Calc_HighestOffense(
    Group_By='Case Info Num',
    Find_Class='A'
)
test5_orig = test5_data.Get_Data()
test5_sub = test5_orig[['Offence Code', 'Code (4)', 'Offence Type Desc', 'Offense Desc']].head(10)
test5_sub

Returning Calculated Data

      Offence Code  Code (4) Offence Type Desc Offense Desc
140        93000.0     930.0           A/B1/B2       MURDER
178        93000.0     930.0           A/B1/B2       MURDER
367        93000.0     930.0           A/B1/B2       MURDER
478        93000.0     930.0           A/B1/B2       MURDER
2269       93000.0     930.0           A/B1/B2       MURDER
2390       93000.0     930.0           A/B1/B2       MURDER
2458       93000.0     930.0           A/B1/B2       MURDER
2472       93000.0     930.0           A/B1/B2       MURDER
2583       93000.0     930.0           A/B1/B2       MURDER
5923       93000.0     930.0           A/B1/B2       MURDER

##### *B1 : View Calculated Offense*

In [64]:
# --- Test 4: Calculate Highest Offense by Class B1 ---
test5_data.Calc_HighestOffense(
    Group_By='Case Info Num',
    Find_Class='B1'
)
test5_orig = test5_data.Get_Data()
test5_sub = test5_orig[['Offence Code', 'Code (4)', 'Offence Type Desc', 'Offense Desc']].head(10)
test5_sub

Returning Calculated Data

      Offence Code  Code (4) Offence Type Desc Offense Desc
140        93000.0     930.0           A/B1/B2       MURDER
178        93000.0     930.0           A/B1/B2       MURDER
367        93000.0     930.0           A/B1/B2       MURDER
478        93000.0     930.0           A/B1/B2       MURDER
2269       93000.0     930.0           A/B1/B2       MURDER
2390       93000.0     930.0           A/B1/B2       MURDER
2458       93000.0     930.0           A/B1/B2       MURDER
2472       93000.0     930.0           A/B1/B2       MURDER
2583       93000.0     930.0           A/B1/B2       MURDER
5923       93000.0     930.0           A/B1/B2       MURDER

##### *B2 : View Calculated Offense*

In [65]:
# --- Test 4: Calculate Highest Offense by Class B2 ---
test5_data.Calc_HighestOffense(
    Group_By='Case Info Num',
    Find_Class='B2'
)
test5_orig = test5_data.Get_Data()
test5_sub = test5_orig[['Offence Code', 'Code (4)', 'Offence Type Desc', 'Offense Desc']].head(10)
test5_sub

Returning Calculated Data

      Offence Code  Code (4) Offence Type Desc Offense Desc
140        93000.0     930.0           A/B1/B2       MURDER
178        93000.0     930.0           A/B1/B2       MURDER
367        93000.0     930.0           A/B1/B2       MURDER
478        93000.0     930.0           A/B1/B2       MURDER
2269       93000.0     930.0           A/B1/B2       MURDER
2390       93000.0     930.0           A/B1/B2       MURDER
2458       93000.0     930.0           A/B1/B2       MURDER
2472       93000.0     930.0           A/B1/B2       MURDER
2583       93000.0     930.0           A/B1/B2       MURDER
5923       93000.0     930.0           A/B1/B2       MURDER

##### *C : View Calculated Offense*

In [66]:
# --- Test 4: Calculate Highest Offense by Class C ---
test5_data.Calc_HighestOffense(
    Group_By='Case Info Num',
    Find_Class='C'
)
test5_orig = test5_data.Get_Data()
test5_sub = test5_orig[['Offence Code', 'Code (4)', 'Offence Type Desc', 'Offense Desc']].head(10)
test5_sub

Returning Calculated Data

,Offence Code,Code (4),Offence Type Desc,Offense Desc
117,102000.0,1020.0,C/E,KIDNAPPING-CONFINE/RESTRAIN/REMOVE PERSO
2593,102000.0,1020.0,C/E,KIDNAPPING-CONFINE/RESTRAIN/REMOVE PERSO
5315,102000.0,1020.0,C/E,KIDNAPPING-CONFINE/RESTRAIN/REMOVE PERSO
5735,102000.0,1020.0,C/E,KIDNAPPING-CONFINE/RESTRAIN/REMOVE PERSO
8046,102000.0,1020.0,C/E,KIDNAPPING-CONFINE/RESTRAIN/REMOVE PERSO
13958,102000.0,1020.0,C/E,KIDNAPPING-CONFINE/RESTRAIN/REMOVE PERSO
14420,102000.0,1020.0,C/E,KIDNAPPING
14438,102000.0,1020.0,C/E,KIDNAPPING
14632,102000.0,1020.0,C/E,KIDNAPPING
15500,102000.0,1020.0,C/E,KIDNAPPING-CONFINE/RESTRAIN/REMOVE PERSO